#+INCLUDE: ./../header.org
#+HTML_LINK_HOME: /
#+HTML_LINK_UP: ./sites/blog.html


* Seguridad en la piscina
:PROPERTIES:
:CUSTOM_ID: seguridad-en-la-piscina
:END:
Llevo un par de días yendo a la piscina, para ser exactos 5 días, he probado distintos horarios y el más interesante es el de las 18:30 - 20:00, además del buen tiempo que hay en esa franja, me gusta la "libertad temporal" que me da para llegar a casa, ducharme y cenar a las 22:00.

El horario no solo me ofrece una comodidad personal también me ha permitido observar (no penséis que pierdo el tiempo es que los dos últimos días no he podido entrar por un oído inflamado...) otros grupos de nado distintos al mío, yo estoy en nado libre, es decir, que no tengo monitor, hago lo que me apetece y la cantidad que puedo (o que creo que puedo), los otros grupos son campamentos de verano (externo) y clases con monitores (interno).

El "quid" de esta entrada lo proporcionan estos dos grupos, el *monitor externo* lo dirige un señor mayor que al parecer lleva toda su vida nadando, grita, insulta, te llama la atención con todos los medios sonoros posibles y a veces habla en inglés para darse a entender a los chavales que no entienden español.

En el otro lado de la balanza tenemos al *monitor interno*, un señor más joven, relajado, con estudiantes de entre 30 y 60 años, son muchos menos que el externo y les habla siempre en español.

El *monitor externo*, al menos a mí, me da más seguridad, si yo diera clases con él sentiría que estoy en lado ganador, supongo que además de lo exigente que son sus ejercicios, su seguridad al hablar marca una gran diferencia.

Es posible que hablar con seguridad de un tema no implique conocimientos concretos sobre el tema, después de todo, yo no puedo hacer un juicio de valor objetivo de los monitores ya que soy un simple *amateur* con perdón de aquellos que realmente entran esa categoría, ambos monitores hacen el mismo trabajo pero con diferente actitud y creo que esa es la verdad diferencia entre porqué escogería el uno o el otro; en cualquier caso me pregunto si es necesario llegar al nivel del *monitor externo* para producir esa aura de seguridad, no creo que insultar o gritar sea la mejor forma de exponer un tema.

Actitud para hablar esa la seguridad que hay en la piscina y que debiera conseguir para hablar delante de 1 o 200000 personas.
* description-post                                                 :noexport:
:PROPERTIES:
:CUSTOM_ID: description-post
:END:
Llevo un par de días yendo a la piscina, para ser exactos 5 días, he probado distintos horarios y el más interesante es el de las 18:30 - 20:00, además del buen tiempo que hay en esa franja, me gusta la "libertad temporal" que me da para llegar a casa, ducharme y cenar a las 22:00.
