#+title: Twitter #1 - Seguridad sobrevalorada
#+AUTHOR: Jorge Benavides M.
#+EMAIL: jorge2@hotmail.es
#+date: <2021-05-19 09:08>
#+SETUPFILE: ~/projects/blog/public_html/org-html-themes/org/theme-bigblow-local.setup
#+description: He quitado el passphrase de mi clave SSH.
#+filetags: contraseñas magit automatización dairy
* [[./../index.org][Un ingeniero en problemas]]
  :PROPERTIES:
  :CUSTOM_ID: index-org-un-ingeniero-en-problemas
  :END:
<2021-05-19 mi. 08:20>
He quitado la contraseña de mi clave ssh, por casualidad he intentado clonar algo desde magit y ha funcionado. ¡Genial! Pero es aún mejor he intentado hacer un pull y ha ido mejor todavía, seguiré haciendo pruebas durante el día.

<2021-05-19 mi. 10:49>
Vale, con el magit puedo trabajar sin problemas, ahora que eliminar lo que había hecho y hacer una función para publicar esto, una lista de tareas que seguir y mucho mucho más, esto no me viene nada bien soy un procrastinador (el primer paso para superarlo es aceptarlo), así que tengo dos opciones, tomarme esto de EMACS con más calma y ponerme a estudiar o hacer la función, seamos realistas quiero que todo funcione así que intentaré hacerlo en 10 minutos sino funciona, apaga y vámonos que tengo examen el sábado.

<2021-05-19 mi. 11:03>
No he podido hacerlo en 10 minutos, gg, sé lo que tengo que hacer pero no sé si es más cómodo usar git.exe o magit, por lo que he mirado en [[https://emacs.stackexchange.com/questions/41572/modify-last-commits-message-and-push-to-upstream][stackexchange]] lo primero es más fácil, seguiré informando.

<2021-05-19 mi. 12:02>
He revisado mi nota de electrónica digital en una tutoría, si un suspenso como una casa, no hay que desanimarse, todavía puedo aprobar, pero tengo que distribuir mejor mi tiempo, aprobar electrónica el sábado y empresa la próxima semana, adiós emacs portable, nos vemos dentro de un mes, hola Twitter/blog, necesito quejarme en algún sitio y twitter trae demasiadas interacciones.

<2021-05-19 mi. 16:22>
No sé que pequeña diferencia puede existir entre entender las leyes de kirckhoff y no entenderlas, si sabes aplicarlas todos los circuitos tienen mucho sentido.
Una cosa más, solo tienes miedo si tienes miedo.

<2021-05-19 mi. 18:42>
He descargado otro libro sobre funciones de transferencia, debo empezar a organizar mi nube/ordenador/biblioteca tengo demasiados libros que me gustaría leer y o que me he leído, uso para consulta, etc... y los tengo dispersos en todos lados, tal vez un .org me ayudaría a organizarlos.
Por cierto el libro que he conseguido es [[https://ieeexplore.ieee.org/book/7470658][Linear Circuit Transfer Functions: An Introduction to Fast Analytical Techniques, Christophe P. Basso]]. Es la primera vez que lo tengo entre mis manos, así que poco puedo decir de él, pero tiene buena pinta lo he ojeado y merece la pena. Debo incluir una sección de reseñas o libros que recomiendo puede ser parte del .org que quiero crear, si tan solo tuviera más tiempo para organizarlo todo y enterarme de como se crean carpetas con org-static-blog.

<2021-05-19 mi. 18:50>
Debería descargar todo de electrónica y pasarlo a un libro, lo haré este domingo, quiero y necesito toda la información del campus, incluye el foro que espero poder guardar.

<2021-05-19 mi. 23:55>
Llevo horas buscando una solución para la función de transferencia de un oscilador Colpitts, como mínimo espero aprenderme el nombre.
