name: Publish Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Your Docker installation steps

      - name: Build Docker container and publish blog
        run: |
          # Your commands to build and publish the blog

      - name: Move generated files to repository
        run: |
          # Your commands to copy the generated files

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add generated_blog/*
          git commit -m "Publish blog files"

      - name: Push changes
        run: |
          git remote set-url origin https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
